### ISSUE TITLE
[BUG] - ⛔ Error: Unable to exchange encryption keys [Windows 11]

### ISSUE THREAD

**Issue by pcgeek86** [veeso/termscp#128]
## Description

When I attempt to connect to my ODROID M1 running Ubuntu Server 64-bit, using SFTP or SCP protocols, I get an error saying `unable to exchange encryption keys`. This happens if I attempt to use `id_rsa` default SSH key or 

![image](https://user-images.githubusercontent.com/466713/196012552-9b7fcbe2-0e59-4593-a519-cb359cd89ddf.png)

## Steps to reproduce

* Use SFTP or SCP to connect to Ubuntu Server 22.04 (ARM or Intel 64-bit)

## Environment

- OS: [e.g. GNU/Linux Debian 10] Windows 11 Dev Preview
- Architecture [Arm, x86_64, ...] Intel / AMD 64-bit
- Rust version
- termscp version 0.10
- Protocol used SFTP and SCP
- Remote server version and name Ubuntu Server 22.04 LTS (ARM and Intel/AMD 64-bit tested)

**Comment by veeso** [comment]
Not our fault, but it looks to be an issue with windows 11 and libssh2 <https://github.com/alexcrichton/ssh2-rs/issues/254> I'm subscribed to this issue to see what's going on.

**Comment by pcgeek86** [comment]
👌🏻

**Comment by ehsanonline** [comment]
I'm having this problem with Windows 10 as Client and Ubuntu 22.04 Server.

**Comment by Himmel-OvO** [comment]
I'm having this problem with rocky as Client and rocky Server.

**Comment by plutonium-239** [comment]
So will this remain closed under `sorcery`?
Facing the same issue, in the logs it is able to locate the correct ssh key file but.... "could not find suitable RSA keys to authenticate with"

**Comment by pierreown** [comment]
Use `openssl` instead of the default `wincng` for `ssh2`:
```toml
[target."cfg(target_family = \"windows\")".dependencies]
remotefs-ftp = { version = "^0.3", features = ["native-tls"] }
remotefs-ssh = { version = "^0.7" }
ssh2 = { version = "^0.9", features = ["openssl-on-win32"] } # enable openssl-on-win32 features 
```
