### ISSUE TITLE
[BUG] Unable to connect to AWS S3

### ISSUE THREAD

**Issue by avoidik** [veeso/termscp#232]
## Description

I was unable to connect to S3 bucket on AWS. There were two major things:
1. termscp is asking me for a password when I try to connect via CLI, `termscp s3://bucket-name@eu-central-1:exported-creds:/`
2. termscp is giving me an error like `[ERROR]: Could not scan current directory: could not stat file (Could not deserialize result  custom: missing field 'Name')` if I try to connect to S3 from the bookmark or via TUI

there is no issue with the credentials, as `aws sts get-caller-identity --profile exported-creds --region eu-central-1` returned my identity

## Steps to reproduce

run from CLI 

```terminal
$ termscp s3://bucket-name@eu-central-1:exported-creds:/
```

or try to create a bookmark (I left an endpoint blank)

## Expected behaviour

termscp should connect to S3 bucket

## Environment

- OS: macos
- Architecture: arm64
- Rust version: N/A
- termscp version: 0.12.3
- Protocol used: S3
- Remote server version and name: AWS S3 API

## Log

```
[ERROR]: Could not scan current directory: could not stat file (Could not deserialize result  custom: missing field 'Name')
```

## Additional information

termscp was installed from [homebrew](https://github.com/veeso/homebrew-termscp)

config.toml

```toml
[user_interface]
text_editor = "/usr/bin/nano"
default_protocol = "SCP"
show_hidden_files = true
check_for_updates = false
prompt_on_file_replace = true
group_dirs = "first"
notifications = true
notification_threshold = 1024
```

bookmarks.toml

```
[bookmarks]

[recents.ISO20240222T120923]
protocol = "S3"

[recents.ISO20240222T120923.s3]
bucket = "bucket-name"
region = "eu-central-1"
profile = "exported-creds"
new_path_style = false
```

SCP works fine, thanks
